# Generated by Django 3.1.2 on 2021-03-19 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginpage', '0002_user_discription'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=70)),
                ('email', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('discription', models.CharField(blank=True, max_length=400)),
                ('is_mentor', models.BooleanField(blank=True, default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
