# Generated by Django 3.1.7 on 2021-03-19 17:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=40)),
                ('image', models.ImageField(blank=True, upload_to='images')),
                ('thoughts', models.TextField(blank=True, max_length=1000)),
                ('question1', models.TextField(blank=True, max_length=1000)),
                ('question2', models.TextField(blank=True, max_length=1000)),
                ('question3', models.TextField(blank=True, max_length=1000)),
                ('question4', models.TextField(blank=True, max_length=1000)),
                ('feedback_uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
