# Generated by Django 3.1.2 on 2021-03-19 09:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Tutorial', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorial',
            name='tutorial_like',
            field=models.ManyToManyField(blank=True, related_name='tutorial_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
