# Generated by Django 3.1.7 on 2021-03-19 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tutorial', '0002_tutorial_tutorial_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_video',
            field=models.FileField(upload_to='img'),
        ),
    ]
